version: '3.8'

services:
  embedding-demo:
    build: .
    image: embedding-demo
    container_name: embedding-demo
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - ./chroma_db:/app/chroma_db
