[project]
name = "homework.02"
version = "0.1.0"
description = "Document search homework"
author = "Jozsef Gulyas"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.4.0",
    "python-dotenv>=1.2.1",
]
